### <span style="color:violet">Data Structures, Functions, Numpy & Pandas</span>

#### Section A: Data Structures & Control Structures

##### <span style="color:orange">1. Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.</span>

In [11]:
# Creating a list of 5 integers
numbers = [10, 20, 30, 40, 50]
print("Original List:", numbers)

# append
numbers.append(60)
print("After append:", numbers)

# extend
numbers.extend([70, 80])
print("After extend:", numbers)

# insert
numbers.insert(2, 25)
print("After insert:", numbers)

# remove
numbers.remove(40)
print("After remove:", numbers)

# pop
numbers.pop()
print("After pop:", numbers)

# index
print("Index of 30:", numbers.index(30))

# count
print("Count of 20:", numbers.count(20))

# sort
numbers.sort()
print("After sort:", numbers)

# reverse
numbers.reverse()
print("After reverse:", numbers)

# clear
numbers.clear()
print("After clear:", numbers)


Original List: [10, 20, 30, 40, 50]
After append: [10, 20, 30, 40, 50, 60]
After extend: [10, 20, 30, 40, 50, 60, 70, 80]
After insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove: [10, 20, 25, 30, 50, 60, 70, 80]
After pop: [10, 20, 25, 30, 50, 60, 70]
Index of 30: 3
Count of 20: 1
After sort: [10, 20, 25, 30, 50, 60, 70]
After reverse: [70, 60, 50, 30, 25, 20, 10]
After clear: []


##### <span style="color:orange">2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.</span>

In [20]:
students = ("Amit", "Riya", "Karan")

# Attempting to change second element
students[1] = "Sneha"


TypeError: 'tuple' object does not support item assignment

##### <span style="color:orange">3. Create a set of integers with some duplicate values. Print the set and explain the output.</span>

In [27]:
num_set = {1, 2, 3, 4, 4, 5, 5}
print(num_set)
print("Sets automatically remove duplicate values, so each element appears only once.")

{1, 2, 3, 4, 5}
Sets automatically remove duplicate values, so each element appears only once.


##### <span style="color:orange">4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.</span>

In [31]:
person = {
    "name": "Rahul",
    "age": 24,
    "city": "Delhi"
}

# Update age
person["age"] = 25

# Add email
person["email"] = "rahul@gmail.com"

print(person)


{'name': 'Rahul', 'age': 25, 'city': 'Delhi', 'email': 'rahul@gmail.com'}


##### <span style="color:orange">5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.</span>

In [35]:
age = 18

if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")


Eligible to vote


##### <span style="color:orange">6. Given a 'marks' variable, print the grade: - 90 and above: 'A' - 75–89: 'B' - 50–74: 'C' - Below 50: 'Fail'</span>

In [39]:
marks = 78

if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Fail")


Grade: B


##### <span style="color:orange">7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.</span>

In [46]:
num = 6

if num > 0:
    print("Positive number")
    if num % 2 == 0:
        print("Even number")
    else:
        print("Odd number")
elif num == 0:
    print("Number is zero")
else:
    print("Negative number")


Positive number
Even number


# Section B: NumPy

In [49]:
import numpy as np


##### <span style="color:orange">8. Create: - A scalar using np.array(5) - A 1D array with values 1 to 5 - A 2D array (2x3) with values from 10 to 60 in steps of 10</span>

In [53]:
# Scalar
scalar = np.array(5)
print("Scalar:", scalar)

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

# 2D array (2x3)
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60]])
print("2D Array:\n", arr_2d)


Scalar: 5
1D Array: [1 2 3 4 5]
2D Array:
 [[10 20 30]
 [40 50 60]]


##### <span style="color:orange">9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().</span>

In [59]:
random_array = np.random.randint(0, 101, size=(4, 4))
print(random_array)


[[22 72 46 48]
 [45 65 96 53]
 [17 48  0 50]
 [39 77 27 36]]


##### <span style="color:orange">10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.</span>

In [64]:
import pandas as pd

array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

df_np = pd.DataFrame(array, columns=["A", "B", "C"])
print(df_np)


   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


# Section C: Exploring Pandas

##### <span style="color:orange">11. Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then: - Use .info(), .describe() - Select 'Name' and 'City' columns - Drop 'City' column - Fill any missing values in 'Salary' column with the mean - Remove any duplicate rows</span>

##### DataFrame Operations

In [70]:
data = {
    "Name": ["Amit", "Riya", "Karan", "Neha", "Rahul",
             "Amit", "Sneha", "Vikram", "Pooja", "Riya"],
    "Age": [25, 23, 27, 24, 26, 25, 28, 29, 22, 23],
    "City": ["Mumbai", "Pune", "Delhi", "Delhi", "Mumbai",
             "Mumbai", "Pune", "Bangalore", "Chennai", "Pune"],
    "Salary": [50000, 48000, None, 52000, 51000,
               50000, 60000, 65000, None, 48000]
}

df = pd.DataFrame(data)
df


Name  Age       City   Salary
0    Amit   25     Mumbai  50000.0
1    Riya   23       Pune  48000.0
2   Karan   27      Delhi      NaN
3    Neha   24      Delhi  52000.0
4   Rahul   26     Mumbai  51000.0
5    Amit   25     Mumbai  50000.0
6   Sneha   28       Pune  60000.0
7  Vikram   29  Bangalore  65000.0
8   Pooja   22    Chennai      NaN
9    Riya   23       Pune  48000.0

##### DataFrame Info

In [72]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


##### DataFrame Description

In [74]:
df.describe()


Age        Salary
count  10.000000      8.000000
mean   25.200000  53000.000000
std     2.299758   6164.414003
min    22.000000  48000.000000
25%    23.250000  49500.000000
50%    25.000000  50500.000000
75%    26.750000  54000.000000
max    29.000000  65000.000000

##### Select Name & City

In [76]:
df[["Name", "City"]]


Name       City
0    Amit     Mumbai
1    Riya       Pune
2   Karan      Delhi
3    Neha      Delhi
4   Rahul     Mumbai
5    Amit     Mumbai
6   Sneha       Pune
7  Vikram  Bangalore
8   Pooja    Chennai
9    Riya       Pune

##### Drop City Column

In [78]:
df = df.drop(columns=["City"])
df


Name  Age   Salary
0    Amit   25  50000.0
1    Riya   23  48000.0
2   Karan   27      NaN
3    Neha   24  52000.0
4   Rahul   26  51000.0
5    Amit   25  50000.0
6   Sneha   28  60000.0
7  Vikram   29  65000.0
8   Pooja   22      NaN
9    Riya   23  48000.0

##### Fill Missing Salary with Mean

In [80]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
df


Name  Age   Salary
0    Amit   25  50000.0
1    Riya   23  48000.0
2   Karan   27  53000.0
3    Neha   24  52000.0
4   Rahul   26  51000.0
5    Amit   25  50000.0
6   Sneha   28  60000.0
7  Vikram   29  65000.0
8   Pooja   22  53000.0
9    Riya   23  48000.0

##### Remove Duplicate Rows

In [82]:
df = df.drop_duplicates()
df


Name  Age   Salary
0    Amit   25  50000.0
1    Riya   23  48000.0
2   Karan   27  53000.0
3    Neha   24  52000.0
4   Rahul   26  51000.0
6   Sneha   28  60000.0
7  Vikram   29  65000.0
8   Pooja   22  53000.0